### ISSUE TITLE
[Ch7, 7.9.2] Equation 7.61

### ISSUE THREAD

**Issue by nicolasrosa** [gaoxiang12/slambook-en#41]
Hello @gaoxiang12,

Could you help me understand the following code and the Equation (7.6.1) and Listing (7.17)?

```
_jacobianOplusXi.block<3, 3>(0, 0) = -Eigen::Matrix3d::Identity();
_jacobianOplusXi.block<3, 3>(0, 3) = Sophus::SO3d::hat(P1_est);
```

1. Why the Jacobian Matrix is 3x3? In this case, shouldn't it be a 3x6 matrix?
2. How do you get to Equation 7.6.1? Here, it's how I calculated so far:

**UPDATE: The following proof is wrong!!!**

<details><summary>CLICK HERE TO SEE</summary>
<p>

![CodeCogsEqn](https://user-images.githubusercontent.com/7122146/113779926-cffc1680-9704-11eb-8f0a-becee7e1e737.gif)

![CodeCogsEqn (1)](https://user-images.githubusercontent.com/7122146/113779927-d094ad00-9704-11eb-8f6b-e48856806272.gif)

![CodeCogsEqn (3)](https://user-images.githubusercontent.com/7122146/113780564-c4f5b600-9705-11eb-94bb-1aa54721d11a.gif)

Do you see something wrong?

</p>
</details>

**Comment by gaoxiang12** [comment]
Hi @nicolasrosa ,
You don't need to write out the elements in the error vector. Just use the matrix form.
In chapter 4.3.5 we've shown that:
![image](https://user-images.githubusercontent.com/6635511/113800349-5e19e080-9789-11eb-94f6-30785a3cbeb6.png)

In ICP, our error is defined as:
![image](https://user-images.githubusercontent.com/6635511/113800464-8f92ac00-9789-11eb-8c29-f08502ec3cdc.png)
or p_i - T p'_i if we use transform instead of rotation plus translation. 

If you use the transform matrix T, remember you should remove the fourth row of Tp'_i. Hence, the fourth row of the Jacobian matrix should also be discarded. So it is a 3x6 matrix of: -[I, -(Rp'_i+t)^], or [-I, (Rp'_i+t)^] if we put the minus sign inside the matrix. 

The code:
```
_jacobianOplusXi.block<3, 3>(0, 0) = -Eigen::Matrix3d::Identity();
_jacobianOplusXi.block<3, 3>(0, 3) = Sophus::SO3d::hat(P1_est);
```

means we set the 3x3 block at index (0,0) as -I, and also set the 3x3 block at (0,3) to (Rp'_i+t)^, which is the same as what we write in the equation.

See https://eigen.tuxfamily.org/dox/group__TutorialBlockOperations.html if you are unfamiliar with Eigen's block operations. It's more convenient than assigning the matrix elements one by one.

**Comment by nicolasrosa** [comment]
Hello @gaoxiang12,

Thank you for your prompt reply!

![CodeCogsEqn (5)](https://user-images.githubusercontent.com/7122146/113909671-53257700-97ae-11eb-871c-0404a42d33d4.gif)

Yeah... As you noticed I was zero familiar with these block operations. Thank you for pointing me out.
